### ISSUE TITLE
Where do I get API ID from?

### ISSUE THREAD

**Issue by ajmalafif** [dorelljames/sanity-plugin-netlify-deploy-status-badge#3]
hello! 

I managed to the OAuth but not sure where do I get `apiId` from Netlify. Thank you for the help and cant wait to use this plugin!

![Settings](https://user-images.githubusercontent.com/827167/119254646-096fdf00-bbea-11eb-9767-055e1ec38c2c.jpg)

![Netlify](https://user-images.githubusercontent.com/827167/119254641-04129480-bbea-11eb-93be-5d6da7b35450.jpg)

**Comment by ajmalafif** [comment]
I realized I am not using `*.sanity.studio` and using self-hosted on Netlify for my Sanity Studio. I am getting this error even though I am using the correct URL for my hosted sanity studio: 

![image](https://user-images.githubusercontent.com/827167/119258287-98d1be00-bbfb-11eb-9c3f-c4de83b660a2.png)

**Comment by dorelljames** [comment]
@ajmalafif In Netlify app, go to your site and click **Site Setting**, you'll find your `apiId` from there. Please see screenshot below as an example

![image](https://user-images.githubusercontent.com/977413/119334490-c2ebb480-bcbd-11eb-8707-989d26fe4854.png)

Also, for the authorization URL issue, it doesn't matter where your Sanity Studio is hosted. For example, if it's hosted on Netlify, and the URL is `https://samplesanitystudio.netlify.app`, you need to append `/netlify-deploy-status-badge` to it to make it work. See this example, even in localhost it works! I think somehow you're pretty close! 😊

![image](https://user-images.githubusercontent.com/977413/119334944-460d0a80-bcbe-11eb-99fb-9c875cc9bcc7.png)

**Comment by ajmalafif** [comment]
hey yes I can confirm these 2 steps make it works now! Thank you so much!
