### ISSUE TITLE
String appear next to badge on the studio

### ISSUE THREAD

**Issue by mitchuman** [dorelljames/sanity-plugin-netlify-deploy-status-badge#8]
Since Sanity v2.27 or v2.28, the string "netlify-deploy-status-badge" appears next to the badge itself in the studio.

<img width="411" alt="Screen Shot 2022-03-25 at 11 17 50 AM" src="https://user-images.githubusercontent.com/73133191/160178834-b919b7b3-2a30-4a04-976a-67d1d473e0e9.png">

**Comment by dorelljames** [comment]
thank you @mitchuman. will take a look and fix as soon as I can.

**Comment by dorelljames** [comment]
Released version [0.0.4](https://github.com/dorelljames/sanity-plugin-netlify-deploy-status-badge/releases/tag/0.0.4). There's a little padding on the right from the invisible character that's been inserted. I hope that's better than the very long text you've put in here. Thanks
